version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zionet_db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  gateway:
    build:
      context: ./gateway
    ports:
      - "4000:4000"
    volumes:
      - ./gateway:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT1=4000
    depends_on:
      - db

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "5000:5000"
    volumes:
      - ./dashboard:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT2=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=zionet_db
    depends_on:
      - db

  auth:
    build:
      context: ./auth
    ports:
      - "6000:6000"
    volumes:
      - ./auth:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT3=6000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=zionet_db
    depends_on:
      - db

  news:
    build:
      context: ./news
    ports:
      - "7000:7000"
    volumes:
      - ./auth:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT4=7000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=zionet_db
    depends_on:
      - db

  chat:
    build:
      context: ./chat
    ports:
      - "8000:8000"
    volumes:
      - ./auth:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT5=8000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=zionet_db
      - OPENAI_API_KEY="sk-proj-sHGeOzQQE459KJ1A4mYvT3BlbkFJnXNB1GPr6LdiV6nsbIoE"
    depends_on:
      - db

  email:
    build:
      context: ./email
    ports:
      - "9000:9000"
    volumes:
      - ./auth:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT6=9000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=zionet_db
    depends_on:
      - db

volumes:
  db-data:
